data_transforms:
  a_min: 0
  a_max: 255
  img_size: 512  # This value might be different based on your actual images
  use_random_crop: False
  use_rotation: True
  rotation_angle: 10
  use_saturation: False
  saturation: 2
  use_brightness: True
  brightness: 2
  use_horizontal_flip: True
  use_random_scale: True

data:
  name: ArcadeDataset
  root_path: '/home/abdelrahman.elsayed/DIAS'
  data_split_csv: '/home/abdelrahman.elsayed/DIAS/data_split.csv'
  fold_num: 0
  label_list: [0,1]
  label_names: ["Background", "Vein"]
  volume_channel: 3
  negative_to_positive_ratio: -1 
