wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
num_epochs:
  desc: null
  value: 1000
reg_multiplier:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1726417516
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.12.1
      5: 0.17.5
      8:
      - 2
      - 5
      13: linux-x86_64
