sam:
  img_size: 512
  num_classes: 2
  sam_type: "base"

img_type: 'image'
arch: "Prompt Adapted SAM"
use_fdn: False
decoder_training: 'none'
mlp_transform: False

prompts:
  USE_TEXT_PROMPT: True
  NUM_TEXT_REPEAT: 1
  USE_IMAGE_PROMPT: False
  USE_SLICE_NUM: False
  LOCATION: 'prepend'
  DROPOUT: 0
  NUM_TOKENS: 5


decoder_training: none
training:
  optimizer: 'adamw'
  lr: 1e-4
  batch_size: 8
  num_epochs: 200
  schedule_step: 200
  warmup_steps: 1000
  schedular: #put your schedular here
  steps: [5000, 10000]
  decay_factor: 0.1 
  schedule_step_factor: 0.2
  weight_decay: 1e-2
  loss: 'focal+dice'
  reg_multiplier: 0

#TODO: implement logic to parse this params.
use_salt: True
salt:
  type: SALT_LoRA_adapt_shift
  svd_rank_linear: 700
  svd_rank_conv2d: 200
  r_lora: 256

# use_lora: False