sam:
  img_size: 512
  num_classes: 2
  sam_type: "base"

img_type: 'image'
arch: "Prompt Adapted SAM"
use_fdn: False
decoder_training: 'none'
mlp_transform: False

prompts:
  USE_TEXT_PROMPT: True
  NUM_TEXT_REPEAT: 1
  USE_IMAGE_PROMPT: False
  USE_SLICE_NUM: False
  LOCATION: 'prepend'
  DROPOUT: 0
  NUM_TOKENS: 5


decoder_training: full
prompt_encoder: full
training:
  optimizer: 'adamw'
  lr: 1e-4
  batch_size: 8
  num_epochs: 200
  schedule_step: 200
  schedule_step_factor: 0.2
  weight_decay: 1e-2
  loss: 'focal+dice'
  reg_multiplier: 0
  warmup_steps: 1000
  steps: [40000, 80000]
  decay_factor: 10

# use_lora: False