wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1729254085.520614
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 500
reg_multiplier:
  desc: null
  value: 0.01
